In [48]:
import sqlite3
import pandas as pd 
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt

In [49]:
data = pd.read_csv('daily_weather.csv')

In [50]:
data.head(10)

,number,air_pressure_9am,air_temp_9am,avg_wind_direction_9am,avg_wind_speed_9am,max_wind_direction_9am,max_wind_speed_9am,rain_accumulation_9am,rain_duration_9am,relative_humidity_9am,relative_humidity_3pm
0,0,918.060000,74.822000,271.100000,2.080354,295.400000,2.863283,0.00,0.0,42.420000,36.160000
1,1,917.347688,71.403843,101.935179,2.443009,140.471548,3.533324,0.00,0.0,24.328697,19.426597
2,2,923.040000,60.638000,51.000000,17.067852,63.700000,22.100967,0.00,20.0,8.900000,14.460000
3,3,920.502751,70.138895,198.832133,4.337363,211.203341,5.190045,0.00,0.0,12.189102,12.742547
4,4,921.160000,44.294000,277.800000,1.856660,136.500000,2.863283,8.90,14730.0,92.410000,76.740000
5,5,915.300000,78.404000,182.800000,9.932014,189.000000,10.983375,0.02,170.0,35.130000,33.930000
6,6,915.598868,70.043304,177.875407,3.745587,186.606696,4.589632,0.00,0.0,10.657422,21.385657
7,7,918.070000,51.710000,242.400000,2.527742,271.600000,3.646212,0.00,0.0,80.470000,74.920000
8,8,920.080000,80.582000,40.700000,4.518619,63.000000,5.883152,0.00,0.0,29.580000,24.030000
9,9,915.010000,47.498000,163.100000,4.943637,195.900000,6.576604,0.00,0.0,88.600000,68.050000

In [51]:
data.shape

(1095, 11)

In [52]:
data.columns

Index(['number', 'air_pressure_9am', 'air_temp_9am', 'avg_wind_direction_9am',
       'avg_wind_speed_9am', 'max_wind_direction_9am', 'max_wind_speed_9am',
       'rain_accumulation_9am', 'rain_duration_9am', 'relative_humidity_9am',
       'relative_humidity_3pm'],
      dtype='object')

In [53]:
features = ['air_pressure_9am', 'air_temp_9am', 'avg_wind_direction_9am',
       'avg_wind_speed_9am', 'max_wind_direction_9am', 'rain_duration_9am',
       'rain_accumulation_9am']

target = ['max_wind_speed_9am']

In [54]:
data = data.dropna()
data.shape

(1064, 11)

In [55]:
X = data[features]
y = data[target]

** Let us look at a typical row from our features: **

In [56]:
X.iloc[334]

air_pressure_9am          920.519457
air_temp_9am               81.371746
avg_wind_direction_9am    159.722535
avg_wind_speed_9am          2.614439
max_wind_direction_9am    190.369374
rain_duration_9am           0.000000
rain_accumulation_9am       0.000000
Name: 340, dtype: float64

In [57]:
y

      max_wind_speed_9am
0               2.863283
1               3.533324
2              22.100967
3               5.190045
4               2.863283
...                  ...
1090            5.212070
1091            2.371156
1092            3.892276
1093            4.764682
1094            4.451511

[1064 rows x 1 columns]

In [58]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=324)

In [59]:
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [60]:
y_prediction = regressor.predict(X_test)
y_prediction

array([[ 2.44666438],
       [ 3.30818495],
       [ 3.36418206],
       [ 1.91613918],
       [ 2.32057236],
       [19.64129655],
       [ 4.76444817],
       [ 5.26713293],
       [ 1.79260855],
       [ 5.20888803],
       [10.90125885],
       [ 7.37228918],
       [ 9.96959184],
       [11.80449922],
       [15.27071029],
       [ 2.40186543],
       [ 1.95436533],
       [ 6.6273803 ],
       [11.18131495],
       [27.1769888 ],
       [ 7.78452297],
       [ 2.74112796],
       [10.8430872 ],
       [15.63713319],
       [ 5.18736461],
       [11.48771606],
       [ 8.95023577],
       [ 4.02955303],
       [ 1.81971448],
       [14.53228123],
       [11.63821003],
       [ 4.67188312],
       [ 3.95210257],
       [13.54333909],
       [ 5.39973904],
       [ 9.41116904],
       [ 4.18136908],
       [ 8.76634284],
       [ 4.08033559],
       [ 6.64583344],
       [23.34590471],
       [ 3.95718465],
       [10.5227379 ],
       [22.03517337],
       [ 9.55400303],
       [ 8.62530272],
       [ 2.59186254],
       [ 2.59113251],
       [ 3.43204931],
       [ 5.72832054],
       [26.08607268],
       [ 1.87890478],
       [12.43438232],
       [ 6.07959541],
       [ 5.30391295],
       [10.43884018],
       [ 5.35180461],
       [ 3.7656805 ],
       [ 3.70054233],
       [ 2.59882464],
       [ 7.20132079],
       [12.58876738],
       [ 2.19693735],
       [11.25649162],
       [ 5.27648762],
       [ 2.01738103],
       [ 3.75280197],
       [ 7.16764299],
       [ 7.36712109],
       [10.38666788],
       [16.75964988],
       [ 3.04044408],
       [17.95065526],
       [ 1.98715391],
       [ 3.2558998 ],
       [17.73360952],
       [12.35268102],
       [ 5.58725567],
       [ 4.77968862],
       [ 3.01254179],
       [ 2.44926144],
       [20.56591484],
       [ 1.54730551],
       [ 3.08183195],
       [ 3.14960575],
       [ 3.89899412],
       [ 4.23860586],
       [26.30374884],
       [16.14828856],
       [11.1358069 ],
       [ 6.67445023],
       [ 5.31039389],
       [ 8.80412867],
       [21.96526873],
       [12.55386233],
       [ 3.27772953],
       [ 1.63762298],
       [ 7.31596324],
       [ 3.77936346],
       [12.48591636],
       [ 2.81717382],
       [18.51830493],
       [ 1.40106255],
       [ 1.80294199],
       [ 2.69109076],
       [ 2.01329821],
       [ 5.63568709],
       [ 2.92102744],
       [ 2.49667164],
       [ 3.86353852],
       [ 3.3073807 ],
       [ 4.47011807],
       [ 2.54515472],
       [ 6.94920975],
       [ 5.40555363],
       [ 5.54796146],
       [ 1.98109326],
       [ 6.41260708],
       [ 2.76871863],
       [ 4.45015639],
       [ 2.40531846],
       [ 5.18584411],
       [ 1.97709903],
       [14.01400142],
       [ 9.38606842],
       [ 4.63073362],
       [ 2.60862086],
       [ 1.63554449],
       [ 3.94150558],
       [10.8498322 ],
       [ 5.48769608],
       [19.26852139],
       [10.24262478],
       [18.92110434],
       [ 1.87999035],
       [ 2.57224042],
       [ 2.41434168],
       [ 2.72836516],
       [ 3.1159574 ],
       [20.58168545],
       [ 2.49457536],
       [ 4.14083606],
       [11.1490346 ],
       [ 4.05981379],
       [18.92732439],
       [17.75066233],
       [ 2.36858739],
       [ 2.62081792],
       [ 3.15046932],
       [ 4.10900144],
       [ 2.32686032],
       [ 5.14425669],
       [ 8.01402838],
       [ 5.87733246],
       [11.60790375],
       [ 4.11804247],
       [17.67848434],
       [ 7.19038874],
       [ 3.75489736],
       [ 7.75917329],
       [ 6.30225532],
       [ 7.44232455],
       [11.9147249 ],
       [ 5.24999581],
       [ 3.78894851],
       [ 3.20292913],
       [ 1.08660713],
       [ 3.39576747],
       [ 2.640919  ],
       [ 4.05460316],
       [ 2.23495585],
       [ 2.90917352],
       [ 1.51299043],
       [14.23718082],
       [ 1.91420812],
       [ 2.3599645 ],
       [ 4.5539964 ],
       [13.5292481 ],
       [ 4.43401892],
       [ 5.41109383],
       [ 1.39060531],
       [ 2.2039222 ],
       [ 3.46611614],
       [ 3.3194534 ],
       [29.00510457],
       [ 3.13767231],
       [ 6.33046295],
       [ 4.81745798],
       [ 4.68148843],
       [ 3.38251641],
       [ 1.90683705],
       [ 3.68940163],
       [ 2.63052106],
       [12.95754165],
       [ 2.49788817],
       [ 5.118934  ],
       [ 3.5639297 ],
       [ 2.22076895],
       [ 5.24130334],
       [ 5.24068631],
       [ 2.62745465],
       [ 3.66009824],
       [18.75513751],
       [ 9.21993914],
       [ 7.93147567],
       [ 4.70483332],
       [ 3.55484612],
       [ 4.23339283],
       [ 1.89154755],
       [17.66029205],
       [21.22211014],
       [ 2.57113034],
       [ 3.78212777],
       [ 2.74890597],
       [ 6.08883686],
       [ 1.18951032],
       [ 5.82372228],
       [ 8.59354825],
       [ 3.09988569],
       [10.80595127],
       [ 1.47382051],
       [ 6.33876627],
       [ 2.22450783],
       [21.78759579],
       [ 6.30393169],
       [ 9.45879209],
       [ 4.56339708],
       [12.88396042],
       [ 7.99409   ],
       [13.36818074],
       [ 6.41393917],
       [ 3.2200208 ],
       [ 3.76532908],
       [ 4.59199743],
       [ 6.66039855],
       [ 2.06112065],
       [17.07126614],
       [ 6.30953781],
       [ 4.6710393 ],
       [13.15730673],
       [21.96723622],
       [ 2.12057952],
       [ 5.73463828],
       [ 4.12106557],
       [ 4.15788223],
       [ 8.0253444 ],
       [ 7.44569098],
       [ 5.10365811],
       [ 1.99235316],
       [ 2.40103448],
       [ 1.88911373],
       [ 4.63795988],
       [ 3.48945739],
       [ 2.50825597],
       [ 1.87869656],
       [ 2.58231611],
       [16.25747188],
       [ 6.8160265 ],
       [ 2.25186456],
       [ 2.23201223],
       [ 1.88541946],
       [ 5.7897391 ],
       [ 2.6070586 ],
       [ 2.99624182],
       [ 5.69498727],
       [16.04647227],
       [ 3.82435831],
       [ 8.85949744],
       [23.66392228],
       [ 4.52042047],
       [ 5.22599258],
       [ 5.05464174],
       [22.21270131],
       [ 2.6709532 ],
       [18.95765785],
       [ 4.13132275],
       [ 6.47611213],
       [ 3.36443264],
       [25.92472412],
       [17.72041965],
       [ 2.30435914],
       [ 5.00063193],
       [12.56810362],
       [ 7.48799785],
       [ 2.07348671],
       [ 5.86526541],
       [ 5.27758602],
       [ 2.29304036],
       [11.74512254],
       [ 4.26440044],
       [ 2.52513634],
       [ 1.93975488],
       [ 7.36812514],
       [ 1.99455637],
       [ 7.81005634],
       [ 4.9433703 ],
       [ 2.44456128],
       [ 4.22910078],
       [ 3.0333558 ],
       [ 5.2656483 ],
       [ 7.82697007],
       [10.06539827],
       [ 9.7594614 ],
       [ 1.81364408],
       [ 1.73764168],
       [ 7.35569583],
       [ 5.00897004],
       [ 4.92219524],
       [ 6.59356911],
       [ 0.84180627],
       [ 7.05267853],
       [ 9.79406266],
       [25.59143908],
       [ 2.98761971],
       [ 3.55385598],
       [ 5.87651825],
       [ 3.25732817],
       [ 1.80103369],
       [ 5.20271964],
       [ 5.89840474],
       [ 8.50164872],
       [11.17644646],
       [ 9.17204187],
       [ 2.01773014],
       [ 3.36111664],
       [ 3.2464996 ],
       [ 1.87724787],
       [26.00282561],
       [ 1.76820944],
       [ 2.32514962],
       [ 3.47777924],
       [ 2.28738401],
       [ 4.56738186],
       [ 5.45873328],
       [12.1610012 ],
       [ 3.95657358],
       [ 4.72502716],
       [ 3.33816883],
       [ 4.93296223],
       [ 3.57396997],
       [ 5.52982109],
       [ 5.09276144],
       [ 2.4260555 ],
       [11.06759735],
       [ 2.78126536],
       [ 4.03743185],
       [ 6.95355739],
       [ 7.56977977],
       [ 2.08709365],
       [ 3.10887352],
       [ 4.37613685],
       [ 2.23393944]])

In [61]:
y_test.describe()

       max_wind_speed_9am
count          352.000000
mean             6.817839
std              5.800063
min              1.275056
25%              2.903676
50%              4.775867
75%              8.321417
max             29.840780

In [62]:
RMSE = sqrt(mean_squared_error(y_true = y_test, y_pred = y_prediction))
print(RMSE)

0.4820521999227169

** Using decision tree model to see RMSE

In [63]:
regressor = DecisionTreeRegressor(max_depth=20)
regressor.fit(X_train, y_train)

DecisionTreeRegressor(criterion='mse', max_depth=20, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [64]:
y_prediction = regressor.predict(X_test)
y_prediction

array([ 2.3040482 ,  2.89129467,  4.0041226 ,  2.0356154 ,  2.5948504 ,
       18.0521058 ,  4.585727  ,  5.4581336 ,  1.5211192 ,  5.5699806 ,
       10.9386366 ,  6.934514  ,  9.1043458 , 11.1623306 , 15.5914718 ,
        2.6882476 ,  2.20327371,  6.51634708, 10.7596814 , 25.3668996 ,
        7.0016222 ,  2.9527608 , 10.78090554, 14.9651286 ,  4.8317904 ,
       10.23926855,  8.500372  ,  3.7133204 ,  1.8890032 , 14.56586307,
       10.8475151 ,  4.362033  ,  3.8922756 , 13.4440094 ,  4.77104404,
        8.6793272 ,  4.8317904 ,  8.51419256,  3.8922756 ,  5.816044  ,
       23.5549782 ,  4.84472325,  9.4398868 , 22.1904448 ,  9.9096442 ,
        8.6345884 ,  2.6172198 ,  2.6619586 ,  3.4225182 ,  5.40260097,
       25.81563062,  1.77940322, 13.1308378 ,  5.8831522 ,  5.8607828 ,
        9.5741032 ,  5.0107456 ,  4.0488614 ,  3.31059535,  2.6172198 ,
        7.270055  , 12.7281886 ,  2.0803542 , 10.7596814 ,  5.8607828 ,
        1.9685072 ,  3.8251674 ,  7.45194855,  7.4490102 , 10.0885994 ,
       17.55082378,  3.20625449, 17.26493412,  2.23694   ,  3.27684553,
       17.8507812 , 11.7886738 ,  5.0107456 ,  4.7646822 ,  3.1540854 ,
        2.7066974 , 20.54954946,  1.4987498 ,  3.0869772 ,  3.7580592 ,
        3.8475368 ,  4.04837716, 25.6353324 , 16.06785991, 10.9386366 ,
        5.8607828 ,  5.2369387 ,  8.4108944 , 23.19415116, 11.5873492 ,
        3.5333236 ,  1.9461378 ,  6.71396705,  3.467257  , 13.1308378 ,
        2.9527608 , 18.62760708,  1.6105968 ,  1.9237684 ,  3.0646078 ,
        1.8890032 ,  5.2120702 ,  2.572481  ,  2.96930906,  3.68327309,
        3.579104  ,  4.2725554 ,  2.684328  ,  6.51634708,  4.5409882 ,
        5.5476112 ,  2.23694   ,  5.816044  ,  2.9527608 ,  4.84472325,
        2.35267606,  6.39681211,  2.3040482 , 15.211192  ,  9.5964726 ,
        5.0778538 ,  2.65107369,  1.4987498 ,  3.47907586, 10.7596814 ,
        4.733501  , 19.21431385, 10.3825958 , 19.6179638 ,  1.7448132 ,
        2.99447297,  2.42553319,  2.6172198 ,  2.6619586 , 20.11195953,
        3.1764548 ,  4.84472325, 10.9386366 ,  4.1159696 , 18.119214  ,
       17.8507812 ,  2.5948504 ,  2.6619586 ,  3.5119958 ,  4.1159696 ,
        2.2816788 ,  5.8607828 ,  7.4490102 ,  5.7265664 , 11.99709279,
        3.7580592 , 16.98617834,  7.43525955,  4.1159696 ,  7.0016222 ,
        4.921268  ,  7.19263271, 10.8475151 ,  5.0107456 ,  4.1159696 ,
        3.0869772 ,  1.1855782 ,  3.7580592 ,  2.7738056 ,  3.8922756 ,
        2.35281193,  3.1764548 ,  1.4987498 , 15.34401109,  2.3981424 ,
        1.8566602 ,  4.94376454, 13.7124422 ,  5.0778538 ,  5.19004536,
        1.43966808,  2.23694   ,  3.41729136,  3.3330406 , 24.6958176 ,
        2.89129467,  7.493749  ,  4.7199434 ,  5.5476112 ,  3.6462122 ,
        1.9461378 ,  3.3777794 ,  2.7514362 , 12.2584312 ,  2.5501116 ,
        5.5699806 ,  3.5567346 ,  2.572481  ,  5.25635081,  5.06360032,
        3.2659324 ,  3.77111584, 19.11978784,  8.5674802 ,  6.8002976 ,
        4.2725554 ,  4.0041226 ,  3.8251674 ,  1.8890032 , 18.6560796 ,
       22.1009672 ,  2.65107369,  3.84954835,  2.6619586 ,  6.5766036 ,
        1.230317  ,  6.4647566 ,  8.052984  ,  3.0869772 , 11.967629  ,
        1.54267607,  6.51634708,  2.2816788 , 20.97118326,  5.7489358 ,
        9.6635808 ,  5.14677772, 13.12279004,  7.8516594 , 14.24896635,
        6.4647566 ,  3.579104  ,  3.96854065,  4.6528352 ,  7.0910998 ,
        2.0356154 , 17.7389342 ,  4.921268  ,  5.0778538 , 13.42164   ,
       22.19571292,  2.23694   ,  6.375279  ,  3.8922756 ,  4.8541598 ,
        7.91220508,  7.0239916 ,  6.39681211,  1.9685072 ,  2.2816788 ,
        1.83871631,  5.0778538 ,  3.5567346 ,  2.4382646 ,  1.75102826,
        2.6619586 , 15.6362106 ,  7.270055  ,  2.5948504 ,  2.32465355,
        1.77940322,  5.6594582 ,  2.6172198 ,  2.8856526 ,  7.493749  ,
       16.06785991,  3.96854065,  8.6793272 , 25.6353324 ,  5.0778538 ,
        4.8317904 ,  4.80268242, 20.97118326,  2.96930906, 19.21431385,
        4.1159696 ,  5.9502604 ,  3.7580592 , 25.81563062, 17.23625393,
        2.3711564 ,  4.62861152, 12.7058192 ,  7.46531092,  2.23694   ,
        5.40260097,  5.2369387 ,  2.684328  , 12.5716028 ,  4.3396636 ,
        2.572481  ,  1.75102826,  7.0239916 ,  2.2816788 ,  7.46531092,
        5.18554716,  2.36309253,  4.0488614 ,  2.9751302 ,  5.21190955,
        7.6950736 ,  9.6625895 ,  9.5964726 ,  1.9237684 ,  1.54267607,
        6.9568834 ,  5.18455247,  5.21190955,  7.14517459,  1.1855782 ,
        7.0910998 ,  9.3727786 , 25.6353324 ,  2.9751302 ,  3.1988242 ,
        5.5699806 ,  3.1764548 ,  1.77940322,  4.95664842,  6.04716037,
        7.9635064 ,  9.9096442 ,  9.9096442 ,  2.58936995,  3.1988242 ,
        4.0041226 ,  2.0356154 , 25.81563062,  2.23694   ,  2.7066974 ,
        3.8699062 ,  1.96225087,  4.921268  ,  4.733501  , 12.7281886 ,
        3.7580592 ,  4.585727  ,  3.4225182 ,  5.21190955,  3.35541   ,
        5.480503  ,  5.18455247,  1.7448132 , 12.1018454 ,  2.8856526 ,
        3.92509373,  8.11886344,  7.3882197 ,  1.789552  ,  3.0869772 ,
        4.04837716,  2.50300399])

In [65]:
y_test.describe()

       max_wind_speed_9am
count          352.000000
mean             6.817839
std              5.800063
min              1.275056
25%              2.903676
50%              4.775867
75%              8.321417
max             29.840780

In [66]:
RMSE = sqrt(mean_squared_error(y_true = y_test, y_pred = y_prediction))
print(RMSE)

0.6259760063431123